"""
Schema-sync check — verifies Alembic's migrations and the SQLAlchemy
models describe the same schema.

Runs the real `alembic upgrade head` against a scratch database, then
`alembic check` to confirm the result matches what the models describe.
This is the same check you'd run by hand before shipping a migration —
wired into the suite so drift (an ARRAY column in the model but JSONB in
the migration, a new model field with no matching column) fails a test
run instead of surfacing later as a runtime error against a real
database, or not surfacing until someone remembers to check.

Uses a dedicated database (aiiam_schema_check_db), never the
create_all/drop_all-based aiiam_test_db the rest of the suite uses —
mixing the two would leave an orphaned alembic_version table with no
reliable way to know if it's still accurate. See
docker/postgres-init/001-create-test-db.sql.

This test is synchronous, not async: alembic/env.py calls asyncio.run()
internally to run migrations, which raises if called from inside an
already-running event loop — so this can't be a pytest-asyncio test.
"""

import asyncio
import os
from pathlib import Path

import asyncpg
from alembic import command
from alembic.config import Config

BACKEND_DIR = Path(__file__).resolve().parent.parent

SCHEMA_CHECK_DATABASE_URL = os.environ.get(
    "SCHEMA_CHECK_DATABASE_URL",
    "postgresql+asyncpg://aiiam_user:supersecretpassword@localhost:5432/aiiam_schema_check_db",
)


def _reset_schema(database_url: str) -> None:
    """
    Drop and recreate the public schema so this test starts from a
    genuinely empty database every run, regardless of what a previous
    run (or a previous failed run) left behind.
    """
    # asyncpg.connect() wants a plain postgresql:// DSN, not SQLAlchemy's
    # dialect-qualified postgresql+asyncpg://
    dsn = database_url.replace("postgresql+asyncpg://", "postgresql://")

    async def _reset() -> None:
        conn = await asyncpg.connect(dsn)
        try:
            await conn.execute("DROP SCHEMA public CASCADE")
            await conn.execute("CREATE SCHEMA public")
        finally:
            await conn.close()

    asyncio.run(_reset())


def test_migrations_match_models(monkeypatch):
    # alembic/env.py prefers an explicit DATABASE_URL env var over the
    # app's own settings.DATABASE_URL — exactly so this test can point
    # migrations at the schema-check database without touching
    # app.core.config. monkeypatch restores this after the test.
    monkeypatch.setenv("DATABASE_URL", SCHEMA_CHECK_DATABASE_URL)

    _reset_schema(SCHEMA_CHECK_DATABASE_URL)

    config = Config(str(BACKEND_DIR / "alembic.ini"))
    config.set_main_option("script_location", str(BACKEND_DIR / "alembic"))

    command.upgrade(config, "head")

    # Raises alembic.util.exc.AutogenerateDiffsDetected if the resulting
    # schema doesn't match the models — that failure IS the test result.
    command.check(config)
