"""add parent_grant_id to delegation_grants

Revision ID: 0002_delegation_parent_grant
Revises: 0001_initial_schema
Create Date: 2026-09-12 05:17:26.732281+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_delegation_parent_grant'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delegation_grants', sa.Column('parent_grant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_delegation_grants_parent_grant_id'), 'delegation_grants', ['parent_grant_id'], unique=False)
    op.create_foreign_key(None, 'delegation_grants', 'delegation_grants', ['parent_grant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delegation_grants', type_='foreignkey')
    op.drop_index(op.f('ix_delegation_grants_parent_grant_id'), table_name='delegation_grants')
    op.drop_column('delegation_grants', 'parent_grant_id')
    # ### end Alembic commands ###
